# If true, stops the server after a period of inactivity.
enabled: false
# Time after last activity to stop the server.
delay: 3600
# Whether the inactivity timer should begin at startup, or wait for players to join first.
from-startup: false
# System scripts to run before stopping the server due to inactivity.
# These will run only if the server is stopped by this plugin.
scripts: []